[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --baud 921600 --monitor --port /dev/ttyUSB1"

[build]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Trom_functions.x",
  "-C", "target-feature=-loop",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core"]
